// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:mlkem_native/src/mlkem768_bindings.dart')
library;

import 'dart:ffi' as ffi;

/// Name:        crypto_kem_keypair_derand
///
/// Description: Generates public and private key
/// for CCA-secure ML-KEM key encapsulation mechanism
///
/// Arguments:   - uint8_t pk[]: pointer to output public key, an array of
/// length MLKEM{512,768,1024}_PUBLICKEYBYTES bytes.
/// - uint8_t sk[]: pointer to output private key, an array of
/// of MLKEM{512,768,1024}_SECRETKEYBYTES bytes.
/// - uint8_t *coins: pointer to input randomness, an array of
/// 2*MLKEM_SYMBYTES uniformly random bytes.
///
/// Returns:     - 0: On success
/// - MLK_ERR_FAIL: If MLK_CONFIG_KEYGEN_PCT is enabled and the
/// PCT failed.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
///
/// Specification: Implements @[FIPS203, Algorithm 16, ML-KEM.KeyGen_Internal]
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int mlkem768_keypair_derand(
  ffi.Pointer<ffi.Uint8> pk,
  ffi.Pointer<ffi.Uint8> sk,
  ffi.Pointer<ffi.Uint8> coins,
);

/// Name:        crypto_kem_keypair
///
/// Description: Generates public and private key
/// for CCA-secure ML-KEM key encapsulation mechanism
///
/// Arguments:   - uint8_t *pk: pointer to output public key, an array of
/// MLKEM{512,768,1024}_PUBLICKEYBYTES bytes.
/// - uint8_t *sk: pointer to output private key, an array of
/// MLKEM{512,768,1024}_SECRETKEYBYTES bytes.
///
/// Returns:     - 0: On success
/// - MLK_ERR_FAIL: If MLK_CONFIG_KEYGEN_PCT is enabled and the
/// PCT failed.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
/// - MLK_ERR_RNG_FAIL: Random number generation failed.
///
/// Specification: Implements @[FIPS203, Algorithm 19, ML-KEM.KeyGen]
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external int mlkem768_keypair(
  ffi.Pointer<ffi.Uint8> pk,
  ffi.Pointer<ffi.Uint8> sk,
);

/// Name:        crypto_kem_enc_derand
///
/// Description: Generates cipher text and shared
/// secret for given public key
///
/// Arguments:   - uint8_t *ct: pointer to output cipher text, an array of
/// MLKEM{512,768,1024}_CIPHERTEXTBYTES bytes.
/// - uint8_t *ss: pointer to output shared secret, an array of
/// MLKEM_BYTES bytes.
/// - const uint8_t *pk: pointer to input public key, an array of
/// MLKEM{512,768,1024}_PUBLICKEYBYTES bytes.
/// - const uint8_t *coins: pointer to input randomness, an array of
/// MLKEM_SYMBYTES bytes.
///
/// Returns: - 0 on success
/// - MLK_ERR_FAIL: If the 'modulus check' @[FIPS203, Section 7.2]
/// for the public key fails.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
///
/// Specification: Implements @[FIPS203, Algorithm 17, ML-KEM.Encaps_Internal]
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int mlkem768_enc_derand(
  ffi.Pointer<ffi.Uint8> ct,
  ffi.Pointer<ffi.Uint8> ss,
  ffi.Pointer<ffi.Uint8> pk,
  ffi.Pointer<ffi.Uint8> coins,
);

/// Name:        crypto_kem_enc
///
/// Description: Generates cipher text and shared
/// secret for given public key
///
/// Arguments:   - uint8_t *ct: pointer to output cipher text, an array of
/// MLKEM{512,768,1024}_CIPHERTEXTBYTES bytes.
/// - uint8_t *ss: pointer to output shared secret, an array of
/// MLKEM_BYTES bytes.
/// - const uint8_t *pk: pointer to input public key, an array of
/// MLKEM{512,768,1024}_PUBLICKEYBYTES bytes.
///
/// Returns: - 0 on success
/// - MLK_ERR_FAIL: If the 'modulus check' @[FIPS203, Section 7.2]
/// for the public key fails.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
/// - MLK_ERR_RNG_FAIL: Random number generation failed.
///
/// Specification: Implements @[FIPS203, Algorithm 20, ML-KEM.Encaps]
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int mlkem768_enc(
  ffi.Pointer<ffi.Uint8> ct,
  ffi.Pointer<ffi.Uint8> ss,
  ffi.Pointer<ffi.Uint8> pk,
);

/// Name:        crypto_kem_dec
///
/// Description: Generates shared secret for given
/// cipher text and private key
///
/// Arguments:   - uint8_t *ss: pointer to output shared secret, an array of
/// MLKEM_BYTES bytes.
/// - const uint8_t *ct: pointer to input cipher text, an array of
/// MLKEM{512,768,1024}_CIPHERTEXTBYTES bytes.
/// - const uint8_t *sk: pointer to input private key, an array of
/// MLKEM{512,768,1024}_SECRETKEYBYTES bytes.
///
/// Returns: - 0 on success
/// - MLK_ERR_FAIL: If the 'hash check' @[FIPS203, Section 7.3]
/// for the secret key fails.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
///
/// Specification: Implements @[FIPS203, Algorithm 21, ML-KEM.Decaps]
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int mlkem768_dec(
  ffi.Pointer<ffi.Uint8> ss,
  ffi.Pointer<ffi.Uint8> ct,
  ffi.Pointer<ffi.Uint8> sk,
);

/// Name:        crypto_kem_check_pk
///
/// Description: Implements modulus check mandated by FIPS 203,
/// i.e., ensures that coefficients are in [0,q-1].
///
/// Arguments:   - const uint8_t *pk: pointer to input public key, an array of
/// MLKEM{512,768,1024}_PUBLICKEYBYTES bytes.
///
/// Returns: - 0 on success
/// - MLK_ERR_FAIL: If the modulus check failed.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
///
/// Specification: Implements @[FIPS203, Section 7.2, 'modulus check']
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>)>()
external int mlkem768_check_pk(ffi.Pointer<ffi.Uint8> pk);

/// Name:        crypto_kem_check_sk
///
/// Description: Implements public key hash check mandated by FIPS 203,
/// i.e., ensures that
/// sk[768𝑘+32 ∶ 768𝑘+64] = H(pk)= H(sk[384𝑘 : 768𝑘+32])
///
/// Arguments:   - const uint8_t *sk: pointer to input private key, an array of
/// MLKEM{512,768,1024}_SECRETKEYBYTES bytes.
///
/// Returns: - 0 on success
/// - MLK_ERR_FAIL: If the public key hash check failed.
/// - MLK_ERR_OUT_OF_MEMORY: If MLK_CONFIG_CUSTOM_ALLOC_FREE is
/// used and an allocation via MLK_CUSTOM_ALLOC returned NULL.
///
/// Specification: Implements @[FIPS203, Section 7.3, 'hash check']
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>)>()
external int mlkem768_check_sk(ffi.Pointer<ffi.Uint8> sk);

const int MLKEM768_SECRETKEYBYTES = 2400;

const int MLKEM768_PUBLICKEYBYTES = 1184;

const int MLKEM768_CIPHERTEXTBYTES = 1088;

const int MLKEM768_SYMBYTES = 32;

const int MLKEM768_BYTES = 32;
